In [2]:
import pandas as pd
import numpy as np
# Importing the libraries
from tensorflow import keras
from keras.callbacks import ModelCheckpoint
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error 
from matplotlib import pyplot as plt
import seaborn as sb
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')
warnings.filterwarnings('ignore', category=DeprecationWarning)

In [3]:
df = pd.read_csv('train.csv')

a = df.iloc[:,1].values
a = pd.DataFrame({'name': a})
a = a.name.unique()
print(a)
pd.DataFrame(df)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]

,SKU Code,CFA Code,Channel,Quantity,DATE,Secondary Sales Amount STC,Secondary Sales Amount Invoiced,Secondary Sales Amount Returned,Secondary Sales Quantity Invoiced,Secondary Sales Quantity Returned,SKU Combination
0,8,0,1,2,2019-01-01,0.00,0.00,0.0,0.0,0.0,0
1,8,0,1,2,2019-02-01,0.00,0.00,0.0,0.0,0.0,0
2,8,0,1,2,2019-03-01,0.00,0.00,0.0,0.0,0.0,0
3,8,0,1,2,2019-04-01,7103.14,7103.14,0.0,192.0,0.0,0
4,8,0,1,2,2019-05-01,31971.88,31971.88,0.0,864.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...
31280,47,21,2,10,2019-08-01,134452.45,173412.00,2475.0,942.0,14.0,1949
31281,47,21,2,10,2019-09-01,244484.61,317213.00,2171.0,2052.0,13.0,1949
31282,47,21,2,10,2019-10-01,128772.79,166478.21,1518.0,1088.0,9.0,1949
31283,47,21,2,10,2019-11-01,63638.18,93754.01,2280.0,584.0,12.0,1949
31284,47,21,2,10,2019-12-01,102555.59,133454.00,380.0,927.0,2.0,1949

In [4]:
def Regression(X, y):
    from sklearn.model_selection import train_test_split
    from sklearn.linear_model import LinearRegression
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 10)
    regressor = LinearRegression()
    regressor.fit(X_train, y_train)
    y_pred = regressor.predict(X_test)
    return (np.mean(np.abs((y_pred - y_test)/y_test)*100))

In [5]:
def Neural_network(X, y):
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 10)


    NN_model = Sequential()

    # The Input Layer :
    NN_model.add(Dense(128, kernel_initializer='normal',input_dim = X_train.shape[1], activation='relu'))

    # The Hidden Layers :
    NN_model.add(Dense(256, kernel_initializer='normal',activation='relu'))
    NN_model.add(Dense(256, kernel_initializer='normal',activation='relu'))
    NN_model.add(Dense(256, kernel_initializer='normal',activation='relu'))

    # The Output Layer :
    NN_model.add(Dense(1, kernel_initializer='normal',activation='linear'))

    # Compile the network :
    NN_model.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mean_absolute_percentage_error'])
    #NN_model.summary()

    checkpoint_name = 'Weights-{epoch:03d}--{val_loss:.5f}.hdf5' 
    checkpoint = ModelCheckpoint(checkpoint_name, monitor='val_loss', verbose = 1, save_best_only = True, mode ='auto')
    callbacks_list = [checkpoint]

    NN_model.fit(X_train, y_train, epochs=1000, batch_size=32, validation_split = 0.2, callbacks=callbacks_list)

    y_pred = NN_model.predict(X_test)
    return(np.mean(np.abs((y_test - y_pred)*100/y_test)))

In [ ]:
def prepare(city): 
    df2 = df.loc[df['Locations'] == str(city)]
    df2 = df2[~(df2['Forecast'] == 0)]           
    df2 = pd.get_dummies(df2, drop_first = False)
    pd.get_dummies(df2, drop_first = False)                                    # one hot encoding
    X = df2.loc[:,["Sales","SellingPrice"]].values
    X1 = df2.iloc[:,7:18]
    X = np.concatenate((X,X1), axis = 1)
    y = df2.loc[:,["Forecast"]].values
    return X, y